### ISSUE TITLE
(TRANSLATION) add VIP invite email template to sparkpost

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#31]
that is the email template used when company invite VIP directly from the panel

**Comment by az** [comment]
```
Zaproszenie VIP od E-commerce Berlin Expo / VIP invitation from E-commerce Berlin Expo
Inbox

Karolina Michalak - Targi eHandlu <vips@targiehandlu.pl>
10:57 AM (5 minutes ago)
to adam@zygadlewicz.com

Firma E-commerce Berlin Expo zaprasza Cię do strefy VIP na 22. Targach eHandlu w Warszawie! Zaproszenie jest bezpłatne.
Targi odbędą się w czwartek - 27 października 2022- na EXPO XXI (ul. Prądzyńskiego).
4 sceny - 40 Ekspertów oraz 140 stoisk dostawców produktów i usług wspierających handel w Internecie.
Start 10:00.

Strefa VIP to miejsce w którym będziesz miał(a) okazję porozmawiać w komfortowych warunkach z Prelegentami, Wystawcami, innymi VIPami a także napić się wyśmienitej kawy!

Aby przyjąć to bezpłatne zaproszenie skorzystaj z poniższego adresu.

UWAGA: Link jest ważny 24 godziny

https://targiehandlu.pl/exhibitors/ecommerceberlincom?vipcode=7d48cb8cb9e6349c33a07b516c05eb2725ba8306
Do zobaczenia. Zespół Targów eHandlu

Company E-commerce Berlin Expo invites you to the VIP Zone @ Ecommerce Warsaw Expo (October 27th 2022, EXPO XXI Warsaw)
Use the link below to accept invite (link expires after 24hrs)

https://targiehandlu.pl/exhibitors/ecommerceberlincom?vipcode=7d48cb8cb9e6349c33a07b516c05eb2725ba8306
```

I believe you have received such email when testing sending from account.ecomm..... have you got the translation?

**Comment by klaudia2209** [comment]
Yes, I received that e-mail, I saw that today. I will prepare the translation asap. Should I have en and de version or english is enough?

**Comment by az** [comment]
it would be nice to close it ("standard vip flow") today 

it is ONE email ... it can be EN+DE --- up to you.

**Comment by klaudia2209** [comment]
**ENGLISH VERSION ONLY** 

SUBJECT: [Free VIP invitation for E-commerce Berlin Expo - 23.02.2023 - from XXX company]

Good news! 

XXX company - E-commerce Berlin Expo exhibitor - has just invited you to join them at the event’s **VIP Zone.** 

The invitation is completely **free of charge.**

During E-commerce Berlin Expo, industry leaders come together for a one-of-a-kind networking experience: 9000 participants, 250 exhibitors, and 50 mic drop speakers! 

The VIP invitation not only lets you enter the regular event area, but also gives you exclusive access to the VIP Zone, allowing you to get in touch with speakers, exhibitors and other VIPs in comfortable conditions while enjoying delicious coffee.

In order to accept the invitation, please use the link below (valid for 24 hours only!):
<link>

E-commerce Berlin Expo will be held on **February 23, 2023 at STATION-Berlin**, Luckenwalder Str. 4-6. The event begins at **10:00 a.m.**

See you there!

E-commerce Berlin Expo Team

**Comment by az** [comment]
added

**Comment by klaudia2209** [comment]
great, thanks
