### ISSUE TITLE
(EMAIL) Prepare promoninja 2 newsletter

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#75]
Przygotuj please newslettery dot promoninja, ktore nie sa durnym copy-paste poprzednich wiadomości EBE tylko odzwierciedlaja i/lub wykorzystują stan faktyczny

* naliczania punktow polega na zliczaniu "zaangażowanych wizyt" (takiego określenia używamy...na pewno nie ma czegos takiego jak punkt za klik)
* update własnej grafiki odbywa się w materiałach promocyjnych (a nie w company data)
* korzystając z materialow promocyjnych promujesz wlasny profil targowy A TAKZE funkcjonalność związaną z umawianiem się na spotkanie 
* strona z materialami jest publiczna - mozesz ja wyslac do osoby odpowiedzialnej w firmie za promke (INFO DLA CIEBIE : nie trzeba wysylac linka logujacego) 

wersja TEH dla referencji - https://github.com/eventjuicer/services/blob/master/resources/views/emails/company/teh22-promoninja-intro-pl.blade.php 

oraz 

https://github.com/eventjuicer/services/blob/master/resources/views/emails/company/teh22-promote-pl.blade.php

**Comment by klaudia2209** [comment]
ENGLISH VERSION (GERMAN VERSION SOON) 

SUBJECT: Join the Exhibitor's Promo Contest! | EBE 2023

@component('mail::message')
 
# Hello {{ array_get($profile, "fname") }},

We’re in the final stretch before the E-commerce Berlin Expo. All hands on deck, because we have prepared an exclusive exhibitor contest for you. There are amazing prizes on offer, including: a video interview, early-bird sales access for EBE2024 booths, a mega package of invitations, and more!

To win the competition, you’ll need to collect as many points as possible! How can you earn them? By sharing a link connected to the promo materials that promote your participation in the Expo and invite your clients to join the Event.

You can find ready-to-share materials on your Exhibitor platform in the **Promo materials** section. Simply click on them to find the link.

## Promo materials

@component('mail::button', ['url' => $accountUrlPromote])
Promo materials page for your company
@endcomponent

**Your promo materials page is public**, allowing you to share the link with your marketing team or anyone else who may want to share the materials on your company’s social media. 

All promo materials are connected to a special link that directs to the Exhibitor’s public profile, where visitors can: 
discover more about your company and see what you have to offer
check your booth location at the EXPO
arrange a meeting with you by the booth

**One user's engaged visit to your public profile made through your customised link earns you one point.** More points = greater chance of winning prizes! 

If you prefer to share your own promo materials, you can add them at the bottom of the promo materials page (click ‘edit’ near the image) and use the raw link. 

Do you want to check your position in the contest or find out more about different prizes? Simply navigate to the Promotion –> Ranking section. 

The best part is that winning one prize doesn’t exclude others – you are eligible to receive multiple prizes simultaneously!

**The Exhibitor Contest ends on February 20, 2023, 11:59 PM CET.**

If you have any questions, let me know and I’d be happy to help. Good luck! 

Best regards, 

@endcomponent

**Comment by klaudia2209** [comment]
SUBJECT: Join the Exhibitor's Promo Contest! | EBE 2023

@component('mail::message')
 
Hello {{ array_get($profile, "fname") }},

We’re in the final stretch before the E-commerce Berlin Expo. All hands on deck, because we have prepared an exclusive exhibitor contest for you. There are amazing prizes on offer, including: a video interview, early-bird sales access for EBE2024 booths and more!

To win the competition, you’ll need to collect as many points as possible! How can you earn them? By sharing a link connected to the promo materials that promote your participation in the Expo and invite your clients to join the Event.

You can find ready-to-share links with promo materials on your Exhibitor platform in the **Promo materials** section. Simply click on them to find the link.

@component('mail::button', ['url' => $accountUrlPromote])
Promo materials page for your company
@endcomponent

**Your promo materials page is public**, allowing you to share the link with your marketing team or anyone else who may want to share the materials on your company’s social media. 

All promo materials are linked to your exhibitor’s public profile, where visitors can:
discover more about your company and see what you have to offer
check your booth location at the EXPO
arrange a meeting with you by the booth

**One user's engaged visit to your public profile made through your customised link earns you one point.** More points = greater chance of winning prizes! 

Do you want to check your position in the contest or find out more about different prizes? Simply navigate to the Promotion –> Ranking section. 

The best part is that winning one prize doesn’t exclude others – you are eligible to receive multiple prizes simultaneously!

**The Exhibitor Contest ends on February 20, 2023, 11:59 PM CET.**

If you have any questions, let me know and I’d be happy to help. Good luck! 

Best regards, 

@endcomponent

**Comment by az** [comment]
temat zmieniam na Promote your exhibitor's profile and get additional benefits.

**Comment by az** [comment]
@klaudia2209 

kilka rzeczy musialem pozmieniac bo imo nie byly zrozumiale


@component('mail::message')
 
Hello {{ array_get($profile, "fname") }},

We’re in the final stretch before the E-commerce Berlin Expo. All hands on deck, because we have prepared an exclusive exhibitor contest for you. There are amazing prizes on offer, including: a **video interview, early-bird sales access for EBE2024 booths and more!**

**To participate the competition, you’ll need to promote your public exhibitor's profile.** When directing your clients, partners and internet audience to your public profile - you promote your participation in the Expo and collect points and move up the ranking! 

**You can find ready-to-use, customized, promotional materials under the link below. All promo materials are linked to your exhibitor's profile.**

@component('mail::button', ['url' => $accountUrlPromote])
Promo materials page for your company
@endcomponent

**Your promo materials page URL can be send to PR team**. Just copy the URL from the browser address bar - after you sign into your panel using the link above - and send it to your colleagues.

Your exhibitor’s public profile has multi functions. Visitors can:

**arrange a meeting with you by the booth** (NEWLY ADDED)

discover more about your company and see what you have to offer

check your booth location at the EXPO

Do you want to check your position in the contest or find out more about different prizes? Simply navigate to the Promotion –> Ranking section. 

The best part is that winning one prize doesn’t exclude others – you are eligible to receive multiple prizes simultaneously!

**The Exhibitor Contest ends on February 20, 2023, 11:59 PM CET.**

If you have any questions, let me know and I’d be happy to help. Good luck! 

Best regards, 

{{$footer}}

@endcomponent
